#!/data/data/com.termux/files/usr/bin/bash

#modpes
su -c settings put global airplane_mode_on 1
su -c am broadcast -a android.intent.action.AIRPLANE_MODE
su -c settings put global airplane_mode_on 0
su -c am broadcast -a android.intent.action.AIRPLANE_MODE

#filex
su -c am force-stop ua.browser.operator784
su -c am force-stop jd.cdyjy.overseas.market.indonesia
su -c am force-stop com.google.android.webview
su -c rm -rf /sdcard/Android/data/
su -c am kill-all

exit 0