#!/data/data/com.termux/files/usr/bin/bash

pkg install pwgen
Pkg install termux-api

su -c pm install -r -d de.apk
su -c pm install anon.apk
su -c pm install api.apk

yes | cp -fr /source/file /destination



echo "Update selesai"

