#!/data/data/com.termux/files/usr/bin/bash

#modpes
su -c settings put global airplane_mode_on 1
su -c am broadcast -a android.intent.action.AIRPLANE_MODE
su -c settings put global airplane_mode_on 0
su -c am broadcast -a android.intent.action.AIRPLANE_MODE

#start DE
su -c am start -S -W gem.bix.de/gem.bix.de.MainActivity
sleep 1
su -c input keyevent TAB TAB TAB ENTER TAB ENTER
sleep 1
su -c input keyevent TAB ENTER 
sleep 1
su -c input keyevent DPAD_LEFT DPAD_LEFT DPAD_LEFT ENTER DPAD_RIGHT ENTER

#filex
su -c am force-stop ua.browser.operator784
su -c am force-stop jd.cdyjy.overseas.market.indonesia
su -c am force-stop com.google.android.webview
su -c rm -rf /sdcard/Android/data/
su -c am kill-all
sleep 1

su -c am start -S ua.browser.operator784/.MainActivity
sleep 8

#username
U=$(pwgen "$(shuf -i 8-20 -n 1)" 1)
su -c input text "$U"
echo "$U" | termux-clipboard-set
su -c input keyevent ENTER
sleep 2

#password
su -c input text "saciladh1"
su -c input keyevent ENTER
sleep 2

#nama
su -c input text "$(shuf -n 1 f)"
su -c input keyevent TAB
su -c input text "$(shuf -n 1 m)"
su -c input keyevent ENTER
sleep 2

#tanggal
su -c input keyevent TAB ENTER
sleep 1
su -c input swipe 540 "$(shuf -i 1100-1300 -n 1)" 540 "$(shuf -i 300-1000 -n 1)"
sleep 1
su -c input tap 540 "$(shuf -i 300-1300 -n 1)"

#bulan
su -c input keyevent TAB ENTER
sleep 1
su -c input tap 540 "$(shuf -i 300-1300 -n 1)"

#tahun
su -c input keyevent TAB
su -c input text "$(shuf -i 1970-2005 -n 1)"
su -c input keyevent ENTER

exit 0
